name: rocknroll
favicon: null
layout_spectrum: 0.7293335848953575
typography_spectrum: 0.06487418850883842
title: The Music Photography Portfolio by Marc Mennigmann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4835536596365273
  lightness: 0.9459775928407907
  saturation: 0.8195539466105402
  rhythmicContrast: 0.892881594132632
purpose: []
