name: rocknroll
favicon: null
layout_spectrum: 0.45618
typography_spectrum: 0.22602
title: The Music Photography Portfolio by Marc Mennigmann
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#fefefe'
    - '#5a5a5a'
    - '#c8c8c8'
    - '#848484'
  brandStrength: 0.4835536596365273
  lightness: 0
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
